### ISSUE TITLE
SOMEONE PLEASE PUSH CHANGES

### ISSUE THREAD

**Issue by remotevase** [ImagicalMine/imagicalmine.github.io#3]
We have made plenty of changes to this website, but we have a problem. 
It doesn't automatically push changes from github to imagicalmine.net
Can anyone push changes, or at least set up auto push?

**Comment by 0-Eclipse-0** [comment]
Github can't connect via FTP

**Comment by keithkfng** [comment]
Done.

**Comment by remotevase** [comment]
Yay!
